research_task:
  description: >
   使用不同软件上的评论数据集对股民关于特定公司或者股票的行情态度进行深入研究。
  expected_output: >
    列出你认为其中重要的评论，尽可能多但是保证不重复；同时不重复的统计正面/负面/中性的评论各有多少条。
  agent: researcher

reporting_task:
  description: >
    阅读你收到的重要的评论和评论情绪统计结果，并就此给出两份市场态度报告。
  expected_output: >
    两个完整的 Markdown 格式 报告，报告一基于重要评论进行逐条评论者情绪分析，包含每一条重要评论，并且每个都有完整的分析；报告二基于评论情绪统计结果，分析市场总体情绪并且量化为0到1中的一个值（其中0表示完全悲观，1表示完全乐观）。（两篇报告均不带 '```' 代码标记）
  agent: reporting_analyst
